name: build image
on:
#   push:
#     branches:
#       - main
#   pull_request:
  workflow_dispatch:
jobs:
  build-image:
    runs-on: ubuntu-24.04
    container:
      image: dzagob/debian:custom-tools-alpine-root
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: verify command
        run: |
          ls -la
          pwd
          docker --version