name: build image
on:
#   push:
#     branches:
#       - main
#   pull_request:
  workflow_dispatch:
jobs:
  build-image:
    runs-on: ubuntu-24.04
    container:
      image: dzagob/debian:custom-tools-alpine-root
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: verify command
        run: |
          ls -la
          pwd
          docker --version
      
      - name: build image with pip python
        working-directory: ./python_codes/python-w-pip/
        run: |
          docker build -t dzagob/python_app:pip .

      - name: build image with uv python
        working-directory: ./python_codes/python-w-uv/
        run: |
          docker build -t dzagob/python_app:uv .
          docker images