name: data-mesh-hands-on
on:
#   push:
#     branches:
#       - main
#   pull_request:
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on:
      labels: my_runner_001
    services:
      # DevOps cung cấp sẵn DB để test, Dev không cần cài
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ecommerce_mesh
        ports:
          - 5432:5432
        # Health check để đảm bảo DB sẵn sàng trước khi chạy test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create virtual env
        run: |
          mkdir -p venv
          python3 -m venv venv

      - name: Install Dependencies
        working-directory: ./handson-datamesh
        run: |
          source ../venv/bin/activate
          pip install -r requirements.txt